### ISSUE TITLE
Gitporter update-all should be limited to sessions within the last 30 days

### ISSUE THREAD

**Issue by JuliusJaenchen** [konstantinlob/gitalytics.org#63]
The gitporter update-all command updates all sessions in the database. However, only sessions that have been active within the last 30 days should be updated, to prevent an unnecessary load in the long-term

**Comment by roriwa** [comment]
I'm for 90 days. (at least 60). I mean I wouldn't visit this website every month.
my optionion
last_seen + 60d < now => no updating
last_seen + 6m < now => deleting session

**Comment by JuliusJaenchen** [comment]
We'll worry about deleting much later. I think that would only become necessary if our database grows too large. And even then we should consider doing a soft delete first.
But that can wait until long after our deadline.
