### ISSUE TITLE
missing frontend for selecting active-workspace

### ISSUE THREAD

**Issue by JuliusJaenchen** [konstantinlob/gitalytics.org#67]
The backend endpoints /get-workspaces and /set-active-workspace have been built.
When working with these endpoints, the active workspace is set in an encrypted cookie and is therefore sent on every request. 

Now the frontend needs a corresponding UI, for the user to be able to select his active workspace.

**Comment by roriwa** [comment]
done ([avg-per-w/d/m](https://github.com/konstantinlob/gitalytics.org/tree/avg-per-w/d/m))
